### ISSUE TITLE
Add social icons

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#10]
We'd like 3 icons placed on the bottom left, one for taka, facebook and instagram.
They would just be floating circles with "Blog, Facebook, and Instagram" written beneath them. The only one that really need the taxt is blog, but if we do it for one we should probably do it for the other two. I slacked you a png

Example:
![social icons](https://user-images.githubusercontent.com/25754228/49545498-f0d8a680-f881-11e8-9928-4c1336b7b68a.jpg)

Links:
https://www.himalayanacademy.com/blog/taka/

https://www.facebook.com/KauaiHinduMonastery/

https://www.instagram.com/kauaishindumonastery/

**Comment by soapdog** [comment]
Done!

**Comment by JaiNatha** [comment]
I just sent you the icon png's on slack.

They need to be round with a transparent background. Not squares. Sorry, I didn't mean to cause confusion with the mock up.

**Comment by soapdog** [comment]
@JaiNatha I've replaced the icons. You might need to refresh to update the cache.
