### ISSUE TITLE
Add a List to Map Page

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#12]
On the Map page we'd like to add a list for larger screens. This would have all the icon's names. When selected they should select the pin.
You could stick the list icon up near the other three in the upper right.

We could consider including this on mobile as a drawer of sorts, but if that gets too complicated with the map view, we can push that to a later iteration. 

![list](https://user-images.githubusercontent.com/25754228/49546214-d30c4100-f883-11e8-8cf0-4c1788f32f3a.jpg)

**Comment by soapdog** [comment]
I've added the list on the side. Right now it is not working as expected, clicking an item moves the user to that item page. I made this first because it is easier. I am adding the marker selection now.

**Comment by soapdog** [comment]
All working.

![map - kauai hindu monastery virtual tour - firefox nightly 2018-12-15 16 58 21](https://user-images.githubusercontent.com/23247/50045443-aa0d5c80-008a-11e9-8297-39625b8b5aa8.png)

**Comment by JaiNatha** [comment]
The background color isn't working on this list for me. Let's make it an rgba(0,0,0,0.4) or something like that. You could adjust the alpha channel to whatever looks good.

**Comment by soapdog** [comment]
@JaiNatha see if you like this version better. You might need to refresh to see the new version.

![map - kauai hindu monastery virtual tour - firefox nightly 2018-12-19 12 41 59](https://user-images.githubusercontent.com/23247/50220933-906e5c80-038b-11e9-9051-926dbde2bc78.png)

**Comment by JaiNatha** [comment]
The items stopped showing up in the list. Maybe it's just for me...

**Comment by soapdog** [comment]
The JSON for the Palm Corridor was broken and was causing the app to crash. There was an illegal unicode character in it.

**Comment by soapdog** [comment]
Closing because it was already fixed in the past.
