### ISSUE TITLE
Added item - Hanuman

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#13]
This is another list item. Hanuman gets installed Dec 31. So after that I'll be able to add content

**Comment by soapdog** [comment]
@JaiNatha once it is installed and you have a couple photos, we'll add it.

**Comment by JaiNatha** [comment]
I manually created a folder called "hanuman-bronze"

I put a slideshow folder in there with two images for now as something of a placeholder.

**Comment by JaiNatha** [comment]
public_html/virtualtour/points-of-interest/hanuman-bronze

**Comment by JaiNatha** [comment]
Ok, I added all the necessities for the item, but I guess you have to run a build of some kind to create the _cache folder?

**Comment by soapdog** [comment]
The id in the json must the same as the folder name. It was backwards. One of them was `hanuman-bronze` and the other `bronze-hanuman`.

Fixed by making them both `hanuman-bronze`.

![image](https://user-images.githubusercontent.com/23247/74748532-921e0380-5260-11ea-8f17-9a6a819e8b6d.png)
