### ISSUE TITLE
Some icons are coming up Undefined 

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#14]
<img width="252" alt="screen shot 2018-12-05 at 10 59 24 am" src="https://user-images.githubusercontent.com/25754228/49546438-5463d380-f884-11e8-84ee-aa76dc384284.png">

This seems to happen after I've moved something. For example the kaholalele road icon at the very bottom of the map

**Comment by soapdog** [comment]
That was related to #19, the moving of pins broke the json files. I've fixed them back and moving them should work well now (I tried moving a couple and they worked fine)
