### ISSUE TITLE
Image Layout adjustments

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#17]
For all sections where there are multiple thumbs showing up in a list, we'd like images to display with a fixed height rather that the current fixed width. Below is an example from shutter stock. Also please reduce the padding to something similar to this as well:

<img width="1225" alt="screen shot 2018-12-05 at 9 24 13 am" src="https://user-images.githubusercontent.com/25754228/49547115-f2a46900-f885-11e8-821d-0fcc2460083d.png">

**Comment by soapdog** [comment]
Fixed.
