### ISSUE TITLE
Page Background Update

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#22]
We want the page background color to be this #faf7f1
And over thatthe background itself to utilize the himalayanacademy background surface:

/assets/img/bg-page.jpg

**Comment by soapdog** [comment]
@JaiNatha just to clarify, this is for all the pages on the site, or just for the map, or for all pages but the map?

**Comment by JaiNatha** [comment]
All pages, but not the map

**Comment by soapdog** [comment]
Fixed!
