### ISSUE TITLE
gallery page - space between rows

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#26]
cut the space between rows in half

**Comment by soapdog** [comment]
In #23 I've changed how the columns and rows behave. Can you please check if they are good now? Its all flex now, so the spaces are not fixed in pixels but rather in percentages. There are three columns in larger screens and two columns in small ones.

**Comment by JaiNatha** [comment]
Ok. The two columns seems to work. 

Could you change the Gallery titles to h2 instead of h1 and also lose the underline in the title and description. I think you can do that with 'text-decoration: none;'
