### ISSUE TITLE
SVG assets too large for web use

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/khm-virtual-tour#27]
@JaiNatha the SVG assets provided are broken in all designer apps I have here as can be seen on the shot below:

![image](https://user-images.githubusercontent.com/23247/51991847-deef3a80-24a3-11e9-8daa-82e49f8c5995.png)

The images open fine in the browser but fail to open in popular SVG design tools such as Affinity Designer and Corel Gravit Designer (both known for their very good SVG output).

I was checking the images to gauge why I was having so much performance problems here trying to do the layout when I noticed their sizes. They are too heavy for web use. SVG should weight a couple bytes or some kbytes but not megabytes.

The arrows are weighting about 2.5mb. It would be better if they were reworked or even redone in Affinity Designer or Gravit so that they have a better output.

**Comment by JaiNatha** [comment]
Did the ones I sent you work? This is closed right?
