### ISSUE TITLE
Gallery Page - small css tweak

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#29]
http://dev.himalayanacademy.com/virtualtour/#/galleries

Change Gallery titles to h2 instead of h1 and also remove the underline from the link in the title and description. I think you can do that with 'text-decoration: none;'

**Comment by soapdog** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/23247/74748051-ce049900-525f-11ea-8270-b9b67fa7b105.png)
