### ISSUE TITLE
Gallery Page - delete extra page 7 pagination

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#31]
Note on page 7 there are no items but still a page.

**Comment by JaiNatha** [comment]
http://dev.himalayanacademy.com/virtualtour/#/galleries/7

**Comment by JaiNatha** [comment]
I guess we should drop the 7th page, unless we foresee more items than are currently showing

**Comment by soapdog** [comment]
I don't think this is happening anymore.
