### ISSUE TITLE
Change Quad Copter tab Title

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#39]
Currently if I add a video to an item's quad-video folder, the item's tab says 4K video. Let's have it say "Aerial Video"

<img width="1288" alt="Screen Shot 2019-05-08 at 11 47 08 AM" src="https://user-images.githubusercontent.com/25754228/57410720-4abdff00-7187-11e9-8a30-45c05909212d.png">

**Comment by soapdog** [comment]
Now there is no text in that navigation anymore. It is now an icon so this issue is solved.
