### ISSUE TITLE
Main Navbar - Add active tab indication

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#41]
Note the underline in the Item (under "description").

Please add that to the underline for the active navigation when on the Map, Gallery or About pages.

**Comment by JaiNatha** [comment]
![IMG_2040](https://user-images.githubusercontent.com/25754228/58279751-ed0ae480-7d3a-11e9-9fac-7046612dc07c.PNG)

**Comment by JaiNatha** [comment]
That wasn't the best english.

I just mean, underline whatever the active tab is for the main navigation.

**Comment by soapdog** [comment]
Done! It looks like this:

![image](https://user-images.githubusercontent.com/23247/68312793-7d4fa280-00ab-11ea-85b5-83bbdadda75d.png)

Waiting for your approval before copying this to the main site. Right now it is live at:

https://dev.himalayanacademy.com/virtualtour

**Comment by JaiNatha** [comment]
Looks good
