### ISSUE TITLE
Leaflet Icon Bubble - Link to Item page

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#42]
Currently on mobile, the "learn more" link in a icon popup is a little small. 
Let's to this:
1. add a line break before the "learn more"
2. increase the "learn more" font size to 18 or 20px
3. add an <a> around the item's image so that the image is clickable as well. 

<img width="368" alt="Screen Shot 2019-05-23 at 9 20 04 AM" src="https://user-images.githubusercontent.com/25754228/58280489-6eaf4200-7d3c-11e9-9e82-4da0b2d12975.png">
<img width="387" alt="Screen Shot 2019-05-23 at 9 19 51 AM" src="https://user-images.githubusercontent.com/25754228/58280494-70790580-7d3c-11e9-8c26-d6aa4424b26c.png">

**Comment by JaiNatha** [comment]
On another look at this, let's try a button.

BUTTON
style="line-height: 24px;border-radius: 8px;background-color:#8c3945;padding-left: 10px;padding-right: 10px;margin-top: 4px;margin-left: -2px;"

LINK
style="text-decoration: none"

Like this:

<img width="376" alt="Screen Shot 2019-05-23 at 9 36 03 AM" src="https://user-images.githubusercontent.com/25754228/58281178-314bb400-7d3e-11e9-8fa0-53dd3b02e93a.png">


<img width="363" alt="Screen Shot 2019-05-23 at 9 36 26 AM" src="https://user-images.githubusercontent.com/25754228/58281196-3f013980-7d3e-11e9-9d10-c6a9e2defa26.png">

**Comment by soapdog** [comment]
Fixed!

It is live on devhap, looks like this:

![image](https://user-images.githubusercontent.com/23247/68313850-2d71db00-00ad-11ea-9190-30769eb2b3e3.png)

Once you approve, I can copy it to the main site.

**Comment by JaiNatha** [comment]
That'll work
