### ISSUE TITLE
360 image view - Less padding

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#43]
On item pages (I know that page is getting that redesign, but this might still apply) we'd like to make the 360 images bigger by having small margins.

There's two divs, each with generic class names and each giving 20px padding.
these are they:
._5064d2e2
._50219f53

Remove the padding from one and change the other to 10px. So there is only 10px of padding. Or each can be 5px. whatever works.

**Comment by soapdog** [comment]
@JaiNatha is this bug still an issue? Those classes are from the Elm based version and not the current Svelte based version. Can you double-check if this still applies and close the issue if it doesn't?

**Comment by JaiNatha** [comment]
No longer an issue. Closing.
