### ISSUE TITLE
Media div on item page - set height

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#44]
Currently the div resizes when you tab between a video and slideshow, for example.

This bumps the description text up and down. 

We either need to set a height, or apply animations to make the change feel seamless. I get the feeling you'd prefer a set height. 

http://dev.himalayanacademy.com/virtualtour2/index.html?route=/location&location=banana-papaya-grove

**Comment by soapdog** [comment]
I've fixed it the best I could, can you please check it out, @JaiNatha

**Comment by JaiNatha** [comment]
Looks fine
