### ISSUE TITLE
Change slideshow image background to 'white'

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#46]
Aloha Andre

Very small thing. could you change the current "grey" to "white" that shows up for vortical images in a slideshow? thanks.

figure.hero.svelte-fw8eeu {
    width: 600px;
    height: 480px;
    max-width: 600px;
    max-height: 480px;
    text-align: center;
    background: #fff;
    padding: 0;
    margin: 0;

Should look like this:
<img width="1037" alt="Screen Shot 2019-11-06 at 9 04 38 AM" src="https://user-images.githubusercontent.com/25754228/68329106-aacd2980-0074-11ea-8134-1734380d9078.png">

**Comment by JaiNatha** [comment]
Actually, lets do #F3F1EA

Then it will basically disappear

**Comment by soapdog** [comment]
done.

![image](https://user-images.githubusercontent.com/23247/74744169-aad6eb00-5259-11ea-8b28-f92de0b7bae7.png)
