### ISSUE TITLE
Gallaries Tab

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#9]
Assuming this will get fixed with image optimization, but currently if you click galleries, the browser tries to load the entirety of the collection (at least it seems like that) onto your RAM and it never actually works. I guess maybe if I waited long enough and had enough RAM it would.

**Comment by soapdog** [comment]
The problem was some broken JSON files after moving the markers as explained in #19, I've added more comments in that task.
